### Chat
# @name chat
POST {{baseUrl}}/chat/3
Content-Type: text/plain

What can you say about contributions?

### Import documents
# @name import-documents
POST {{baseUrl}}/etl
Content-Type: application/json

{
    "path": "/home/grzegorz/Programowanie/Projekty/doc-repos/test-repo"
}